# Generated by Django 5.1.4 on 2025-01-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
