# Generated by Django 5.1.4 on 2025-02-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('ME', 'Mechanical'), ('EE', 'Electrical')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
